### ISSUE TITLE
[v1.4] ULTIMATE CAP tracker enhancement!!

### ISSUE THREAD

**Issue by tuandingwei** [AY1920S1-CS2103-T16-2/main#142]
- [x] Bugs fix

- [x] Achievement badges

- [x] Implement test cases to increase coverage by ~15%

- [x] UI enhancements

- [x] Enhance find command

- [x] Sort command

- [x] Fix issues brought up in PE1
