### ISSUE TITLE
[v1.3] CAP Tracker features enhancement and testing

### ISSUE THREAD

**Issue by tuandingwei** [AY1920S1-CS2103-T16-2/main#98]
Features
- [x] Calculation of CAP

- [x] Pie Chart for a statistical overview

- [x] Provide Find function for module code and module titles

- [x] UI enhancement to include new layout that accommodates the pie chart and make grades more visible.

Test
- [x] Debugging

- [x] Implement 5 more test cases
